---
- name: Description of what the playbook is doing
  collections:
    - netapp.ontap or cisco.nxos.nxos or netapp.elementsw
  hosts: "{{ hosts | default (netapp) }}"
  vars_files:
    - vars/main.yml
  tasks:
    - block:
        - name: Run playbook name
          include_tasks: tasks/main.yml
          tags:
            - Tags 
            - Go Here
      rescue:
        - name: Failure message
          debug:
            msg:
              - "TASK [Run PLAYBOOK NAME] FAILED. Hints:"
              - 1. Check the failure error message.
              - 2. Check whether the task file exists.
              - 3. Check whether the task file name and extension is correct.


