#SAMPLE MAIN.YML File
#main.yml file for nar_hci_mellanox_deploy

#Primary setup on Mellanox Switches
- block:
    - name: Common setup on Mellanox switches
      include_tasks: ../../tasks/common_setup.yml
      tags:
        - common_setup
        - spanning_tree
        - ipl_mlag
        - storage_mgmt
        - storage_config
        - uplink_config
        - uplink_mlag_config
        - compute_config
  rescue: 
    - name: Failure message
      debug:
        msg:
          - "TASK [Common setup on Mellanox switches] FAILED. Hints:"
          - 1. Check the failure error message.
          - 2. Check whether the task file exists.
          - 3. Check whether the task file name and extension is correct.

# Configure IPL MLAG
- block:
    - name: Create Inter Peer link(IPL) MLAG between ONYX switches
      include_tasks: ../../tasks/ipl_config.yml
      tags:
        - ipl_mlag
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Creating IPL MLAG between ONYX switches] FAILED. Hints:"
          - 1. Check the failure error message.
          - 2. Check whether the task file exists.
          - 3. Check whether the task file name and extension is correct.

# Configure storage MLAG ports
- block:
    - name: Configure ports for storage
      include_tasks: ../../tasks/storage_config.yml
      tags:
        - storage_config
        - spanning_tree
    - name: Configure VLANs for storage
      include_tasks: ../../tasks/storage_iscsi_vlan_config.yml
      tags:
        - storage_config
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Creating storage MLAG] FAILED. Hints:"
          - 1. Check the failure error message.
          - 2. Check whether the task file exists.
          - 3. Check whether the task file name and extension is correct.

#Configure storage management ports
- block:
    - name: Configure storage mgmt ports 
      include_tasks: ../../tasks/storage_mgmt_config.yml
      tags:
        - storage_mgmt
        - spanning_tree
  when: storage_mgmt|bool
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Configuring storage mgmt ports] FAIILED. Hints:"
          - 1. Check the failure error message.
          - 2. Check whether the task file exists.
          - 3. Check whether the task file name and extension is correct.

# Configure individual compute ports
- block:
    - name: Configure compute ports
      vars:
        member: "{{ item.members }}"
        description: "{{ item.description }}"
        speed: "{{ item.speed }}"
      include_tasks: ../../tasks/compute_config_individual.yml
      tags:
        - compute_config
        - spanning_tree
      when: item.mlag_id is not defined or item.mlag_id == None or item.mlag_id|upper == "NA" or item.mlag_id|upper == "N/A" or item.mlag_id == ''
      with_items: "{{ compute_interfaces }}"
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Configuring compute individual ports] FAILED. Hints:"
          - 1. Check the failure error message.
          - 2. Check whether the task file exists.
          - 3. Check whether the task file name and extension is correct.

#Configure Compute MLAG ports
- block:
    - name: Configure the compute ports in MLAG
      vars:
        member: "{{ item.members }}"
        mlag_id: "{{ item.mlag_id }}"
        description: "{{ item.description }}"
        speed: "{{ item.speed }}"
      include_tasks: ../../tasks/compute_config_mlag.yml
      tags:
        - compute_config
        - spanning_tree
      when: item.mlag_id is defined and item.mlag_id != None and item.mlag_id|upper != "NA" and item.mlag_id|upper != "N/A" and item.mlag_id != ''
      with_items: "{{ compute_interfaces }}"
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Configuring compute MLAG ports] FAILED. Hints:"
          - 1. Check the failure error message.
          - 2. Check whether the task file exists.
          - 3. Check whether the task file name and extension is correct.

#Configure Individual Uplinks
- block:
    - name: Configure individual uplinks
      include_tasks: ../../tasks/uplink_config_individual.yml
      tags:
        - uplink_config
        - spanning_tree
      when: not uplink_switch_lacp|bool
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Configuring Individual Uplinks] FAILED. Hints:"
          - 1. Check the failure error message.
          - 2. Check whether the task file exists.
          - 3. Check whether the task file name and extension is correct.

#Configure MLAG Uplinks
- block:
    - name: Configure MLAG uplinks
      include_tasks: ../../tasks/uplink_config_mlag.yml
      tags:
        - uplink_mlag_config
        - spanning_tree
      when: uplink_switch_lacp|bool
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Configuring MLAG uplinks] FAILED. Hints:"
          - 1. Check the failure error message.
          - 2. Check whether the task file exists.
          - 3. Check whether the task file name and extension is correct.
