---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: create aws connector
      include_tasks: create_connector.yml
      tags:
        - aws_connector
      